name: rclone-ui
base: core22
version: '3.5.4'
summary: Cross-platform GUI for rclone & S3
description: |
  The best way to manage your rclone remotes & tasks in a light and easy way.
  Free to use & open source.
grade: stable
confinement: classic
icon: src-tauri/icons/128x128.png

apps:
  rclone-ui:
    command: usr/bin/rclone-ui
    desktop: usr/share/applications/rclone-ui.desktop
    extensions: [gnome]

parts:
  rclone-ui:
    plugin: dump
    source: rclone-ui.deb
    source-type: deb
    stage-packages:
      - libayatana-appindicator3-1
    organize:
      'usr/bin/Rclone UI': usr/bin/rclone-ui
      'usr/share/applications/Rclone UI.desktop': usr/share/applications/rclone-ui.desktop
    override-prime: |
      craftctl default
      sed -i 's|Exec="Rclone UI"|Exec=rclone-ui|g' $CRAFT_PRIME/usr/share/applications/rclone-ui.desktop
